// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
ui_Screen6 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Chart1 = lv_chart_create(ui_Screen6);
lv_obj_set_width( ui_Chart1, 309);
lv_obj_set_height( ui_Chart1, 204);
lv_obj_set_x( ui_Chart1, 5 );
lv_obj_set_y( ui_Chart1, 31 );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_SCATTER);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 150);
lv_chart_set_div_line_count( ui_Chart1, 0, 0);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 0, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);



ui_Header6 = lv_obj_create(ui_Screen6);
lv_obj_set_height( ui_Header6, 25);
lv_obj_set_width( ui_Header6, lv_pct(100));
lv_obj_set_align( ui_Header6, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Header6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header6, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackLabel5 = ui_BackLabel_create(ui_Header6);
lv_obj_set_x( ui_BackLabel5, 0 );
lv_obj_set_y( ui_BackLabel5, -20 );

ui_Header_Title6 = lv_label_create(ui_Header6);
lv_obj_set_width( ui_Header_Title6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Title6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Title6, 0 );
lv_obj_set_y( ui_Header_Title6, -9 );
lv_obj_set_align( ui_Header_Title6, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Header_Title6,"Pressure Enthalpy");
lv_obj_set_style_text_color(ui_Header_Title6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Title6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Time6 = lv_label_create(ui_Header6);
lv_obj_set_width( ui_Header_Time6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Time6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Header_Time6, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Header_Time6,"--:--:--");
lv_obj_set_style_text_color(ui_Header_Time6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Time6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button6 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button6, 100);
lv_obj_set_height( ui_Button6, 80);
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}
