// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#include "../ui.h"

void ui_Screen0_screen_init(void)
{
ui_Screen0 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button01 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button01, 5 );
lv_obj_set_y( ui_Button01, 5 );
lv_obj_set_align( ui_Button01, LV_ALIGN_TOP_LEFT );

ui_Button02 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button02, 110 );
lv_obj_set_y( ui_Button02, 5 );
lv_obj_set_align( ui_Button02, LV_ALIGN_TOP_LEFT );

lv_label_set_text(ui_comp_get_child(ui_Button02, UI_COMP_BUTTON0_LABEL3),"Screen 2");

ui_Button03 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button03, 215 );
lv_obj_set_y( ui_Button03, 5 );

lv_label_set_text(ui_comp_get_child(ui_Button03, UI_COMP_BUTTON0_LABEL3),"Screen 3");

ui_Button04 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button04, 5 );
lv_obj_set_y( ui_Button04, 83 );

lv_label_set_text(ui_comp_get_child(ui_Button04, UI_COMP_BUTTON0_LABEL3),"Screen 4");

ui_Button05 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button05, 110 );
lv_obj_set_y( ui_Button05, 83 );

lv_label_set_text(ui_comp_get_child(ui_Button05, UI_COMP_BUTTON0_LABEL3),"Screen 5");

ui_Button06 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button06, 215 );
lv_obj_set_y( ui_Button06, 84 );

lv_label_set_text(ui_comp_get_child(ui_Button06, UI_COMP_BUTTON0_LABEL3),"Screen 6");

ui_Button07 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button07, 5 );
lv_obj_set_y( ui_Button07, 161 );

lv_label_set_text(ui_comp_get_child(ui_Button07, UI_COMP_BUTTON0_LABEL3),"Screen 7");

ui_Button08 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button08, 110 );
lv_obj_set_y( ui_Button08, 161 );

lv_label_set_text(ui_comp_get_child(ui_Button08, UI_COMP_BUTTON0_LABEL3),"Screen 8");

ui_Button09 = ui_Button0_create(ui_Screen0);
lv_obj_set_x( ui_Button09, 215 );
lv_obj_set_y( ui_Button09, 161 );

lv_label_set_text(ui_comp_get_child(ui_Button09, UI_COMP_BUTTON0_LABEL3),"Screen 9");

lv_obj_add_event_cb(ui_Button01, ui_event_Button01_Button0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button02, ui_event_Button02_Button0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button03, ui_event_Button03_Button0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button04, ui_event_Button04_Button0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button05, ui_event_Button05_Button0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button06, ui_event_Button06_Button0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button07, ui_event_Button07_Button0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button08, ui_event_Button08_Button0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button09, ui_event_Button09_Button0, LV_EVENT_ALL, NULL);

}
