// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#ifndef _UI_COMP_BUTTON0_H
#define _UI_COMP_BUTTON0_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button0
#define UI_COMP_BUTTON0_BUTTON0 0
#define UI_COMP_BUTTON0_LABEL3 1
#define _UI_COMP_BUTTON0_NUM 2
lv_obj_t *ui_Button0_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
