// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#ifndef _UI_COMP_BACKLABEL_H
#define _UI_COMP_BACKLABEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BackLabel
#define UI_COMP_BACKLABEL_BACKLABEL 0
#define _UI_COMP_BACKLABEL_NUM 1
lv_obj_t *ui_BackLabel_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
