// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Thermostat_M5

#include "../ui.h"

void ui_comp_BackLabel_create_hook( lv_obj_t * comp)
{
}

void ui_comp_Button0_create_hook( lv_obj_t * comp)
{
}
