// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#include "../ui.h"


// COMPONENT BackLabel

lv_obj_t *ui_BackLabel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_BackLabel;
cui_BackLabel = lv_label_create(comp_parent);
lv_obj_set_width( cui_BackLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_BackLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_BackLabel, 0 );
lv_obj_set_y( cui_BackLabel, -20 );
lv_label_set_text(cui_BackLabel,"<");
lv_obj_set_style_text_color(cui_BackLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_BackLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_BackLabel, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BACKLABEL_NUM);
children[UI_COMP_BACKLABEL_BACKLABEL] = cui_BackLabel;
lv_obj_add_event_cb(cui_BackLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_BackLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_BackLabel_create_hook(cui_BackLabel);
return cui_BackLabel; 
}

