// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: CoreS3_SLS_Project

#include "../ui.h"


// COMPONENT Button0

lv_obj_t *ui_Button0_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Button0;
cui_Button0 = lv_btn_create(comp_parent);
lv_obj_set_width( cui_Button0, 100);
lv_obj_set_height( cui_Button0, 73);
lv_obj_set_x( cui_Button0, 5 );
lv_obj_set_y( cui_Button0, 5 );
lv_obj_add_flag( cui_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Label3;
cui_Label3 = lv_label_create(cui_Button0);
lv_obj_set_width( cui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label3,"Screen 1");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON0_NUM);
children[UI_COMP_BUTTON0_BUTTON0] = cui_Button0;
children[UI_COMP_BUTTON0_LABEL3] = cui_Label3;
lv_obj_add_event_cb(cui_Button0, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Button0, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Button0_create_hook(cui_Button0);
return cui_Button0; 
}

